#+TITLE: Hellgo
#+STARTUP: overview

At first, this project is so called ~golangtour~ or ~hellogo~...ughhh, boring.

Then, thanks to my clumsy fingers, the misspelling ~hellgo~ for ~hellogo~, coincidentally sounds interesting.

The "hell", is not that hell, not like "infernal" here, it simply means nothing but:

- A /hellgo/ to go?
- What the "hell" to go?
- How the "hell" should I go with go?
- How get the "hell" out of go?
- How dive into the "hell" of go?
- Heil Hitler!(/another misspelling/)
- Hell nonsense!!
- Hell go!!!

* Index

- Basics & Specs
  - [[file:doc/golang-spec.org][The Go Programming Language Specification(Go Blog)]]
  - [[file:doc/effective-go.org][Effective Go(Go Blog)]]
  - [[file:doc/gomod.org][Go Modules: ~go mod init~]]

- Dive & Tour
  - [[file:doc/deepdive-go.org][Ccmouse Golang Course: Deepdive Go]]
  - [[file:doc/unicode-go.org][Unicode Go]]
  - [[file:src/json/parser.go][A Simple JSON Parser Written in Go]]



* LICENSE

#+BEGIN_VERSE
        DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
                    Version 2, December 2004

 Copyright (C) 2020 Eric Wang<wrqatw@gmail.com>

 Everyone is permitted to copy and distribute verbatim or modified
 copies of this license document, and changing it is allowed as long
 as the name is changed.

            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION

  0. You just DO WHAT THE FUCK YOU WANT TO.
#+END_VERSE
